name: tiki_login_example
description: Demonstrates how to use the login plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tiki_login:
    path: ../
  cupertino_icons: ^1.0.5
  uuid: ^3.0.6
  logging: ^1.0.2
  flutter_secure_storage: ^5.0.2
  httpp: ^0.0.4
  firebase_core: ^1.18.0

dependency_overrides:
  crypto: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  flutter_lints: ^2.0.1
