name: login_example
description: Demonstrates how to use the login plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  login:
    path: ../
  cupertino_icons: ^1.0.2
  uuid: 3.0.5
  logging: ^1.0.2
  firebase_core: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  flutter_lints: ^1.0.0
