name: tiki_login
description: flutter lib for login
version: 0.0.14
homepage: https://mytiki.com
repository: https://github.com/tiki/login
issue_tracker: https://github.com/tiki/login/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^9.2.0
  barcode_scan2: ^4.2.0
  lottie: ^1.3.0
  logging: ^1.0.2
  provider: ^6.0.2
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.1.0
  flutter_markdown: ^0.6.10
  email_validator: ^2.0.1
  firebase_dynamic_links: ^4.2.1
  tiki_wallet: ^0.0.18
  httpp: ^0.0.4
  tiki_style: ^0.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4

flutter:
  assets:
    - packages/tiki_login/src/screen_terms/screen_terms_tos.md
    - packages/tiki_login/src/screen_terms/screen_terms_privacy.md