name: tiki_login
description: flutter lib for login
version: 0.0.16
homepage: https://mytiki.com
repository: https://github.com/tiki/login
issue_tracker: https://github.com/tiki/login/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.0.0
  amplitude_flutter: ^3.10.0
  barcode_scan2: ^4.2.1
  lottie: ^1.3.0
  logging: ^1.0.2
  provider: ^6.0.3
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.1.3
  flutter_markdown: ^0.6.10+2
  email_validator: ^2.0.1
  firebase_dynamic_links: ^4.2.6
  tiki_wallet: ^0.0.23
  httpp: ^0.0.4
  tiki_style: ^0.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - packages/tiki_login/src/screen_terms/screen_terms_tos.md
    - packages/tiki_login/src/screen_terms/screen_terms_privacy.md